### ISSUE TITLE
T8A3 Feedback

### ISSUE THREAD

**Issue by JoelT-92** [CS2103AUG2016-T17-C1/main#13]
## User stories

Good job with the user stories.
- You guys may want to include user stories that you considered but decided not to do.
- You may wish to reconsider the priority for these use cases:
  1. As a user, I want to have shortcuts so that I can use the application more efficiently
  2. As an advanced user, I want to customize shortcuts so that I can choose more suitable key combinations

I believe those are nice to have features, but if you think otherwise, you can keep them.
## Use cases

I've read through your use cases, and noticed that they are outdated. In fact, some of the use cases were probably copied and pasted, resulting in the same MSS for different use cases. Also, you are lacking use cases for the other user stories you have. Please brush up on them. You don't have to do them all at one shot, but should incrementally improve it.
## NFRs

Good enough. You may also take a look at the module handbook for some of their NFRs, and list them in your documentation.
## Product Survey

Very well done! Good job including many products.

**Comment by mihnea-arion** [comment]
1. Edited the user stories a bit.
2. Reworked the use cases.
3. Added two more NFRS.
