### ISSUE TITLE
General Feedback for v0.4

### ISSUE THREAD

**Issue by JoelT-92** [CS2103AUG2016-T17-C1/main#30]
## Presentation

Presentation was okay, alas a little clunky. For the final presentation, you should be more prepared eg.
- a story to tell, 
- existing tasks in the program, 
- commands prepared.
## Collate
- Collate was not done properly. Collate should be performed on tests, documentations, and code. Collate is extremely important because you are marked for the things you collated. Having 0 collate will mean that you have done nothing. Please re-read the section `Extract your code for code quality grading` under `V0.4 : The Beta Release` at http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/handbook.html#handbook-project-v04
## Readme
- Please update the picture of your GUI
## Developer Guide
- The architecture, and component diagrams are not up to date.
- If you have included more components, please add their diagrams in.
- Update your use cases for your new commands
- You may wish to give a few examples of interesting test cases, and explain the thinking behind how you arrived at those test cases.
- You may also wish to explain the design of your undo/redo, because there are multiple ways this can be done.
## User guide
- Update the pictures for your GUI
- Remove useless information
  ![image](https://cloud.githubusercontent.com/assets/12592754/19829145/0524342e-9e0c-11e6-80f5-df855679f8a4.png)
- If there are prompts in your program, you can include partial screenshots to show them
- Update your Command Summary section because they will be used extensively during testing.
## AboutUs
- Please update the file to follow the new format

**Comment by mihnea-arion** [comment]
Readme fixed, the appropriate image is now showing
User guide cleaned and updated accordingly

**Comment by mihnea-arion** [comment]
Partially updated Developer guide; diagrams still need updating
Collate should be in proper form now
AboutUs should be in proper form now
